version: "3"

services:
  jackal-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jackal-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/app
    # The bot doesn't need any exposed ports as it connects to Telegram API
